// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Contentful from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as serializers from "../../../../serialization/index.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Entries {
    export interface Options {
        environment?: core.Supplier<environments.ContentfulEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        spaceId: string;
        environmentId: string;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Entry related endpoints
 */
export class Entries {
    protected readonly _options: Entries.Options;

    constructor(_options: Entries.Options) {
        this._options = _options;
    }

    /**
     * Retrieve an entry by ID
     *
     * @param {Contentful.GetEntriesRequest} request
     * @param {Entries.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.entries.get({
     *         spaceId: "yadj1kx9rmg0",
     *         environmentId: "master",
     *         entryId: "1nG4SkuMy0WenQUG6z2aEw"
     *     })
     */
    public get(
        request: Contentful.GetEntriesRequest,
        requestOptions?: Entries.RequestOptions,
    ): core.HttpResponsePromise<Contentful.EntrySchema> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Contentful.GetEntriesRequest,
        requestOptions?: Entries.RequestOptions,
    ): Promise<core.WithRawResponse<Contentful.EntrySchema>> {
        const { spaceId, environmentId, entryId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ContentfulEnvironment.Default,
                `spaces/${encodeURIComponent(this._options.spaceId)}/environments/${encodeURIComponent(this._options.environmentId)}/entries/${encodeURIComponent(entryId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.EntrySchema.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ContentfulError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ContentfulError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ContentfulTimeoutError(
                    "Timeout exceeded when calling GET /spaces/{spaceId}/environments/{environmentId}/entries/{entryId}.",
                );
            case "unknown":
                throw new errors.ContentfulError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a collection of entries
     *
     * @param {Contentful.ListEntriesRequest} request
     * @param {Entries.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.entries.list({
     *         spaceId: "yadj1kx9rmg0",
     *         environmentId: "master",
     *         contentType: "blogPost"
     *     })
     */
    public list(
        request: Contentful.ListEntriesRequest,
        requestOptions?: Entries.RequestOptions,
    ): core.HttpResponsePromise<Contentful.ListEntriesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Contentful.ListEntriesRequest,
        requestOptions?: Entries.RequestOptions,
    ): Promise<core.WithRawResponse<Contentful.ListEntriesResponse>> {
        const { spaceId, environmentId, contentType, cursor, include, skip, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (contentType != null) {
            _queryParams["content_type"] = contentType;
        }

        if (cursor != null) {
            _queryParams["cursor"] = cursor.toString();
        }

        if (include != null) {
            _queryParams["include"] = include.toString();
        }

        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ContentfulEnvironment.Default,
                `spaces/${encodeURIComponent(this._options.spaceId)}/environments/${encodeURIComponent(this._options.environmentId)}/entries`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ListEntriesResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ContentfulError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ContentfulError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ContentfulTimeoutError(
                    "Timeout exceeded when calling GET /spaces/{spaceId}/environments/{environmentId}/entries.",
                );
            case "unknown":
                throw new errors.ContentfulError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
