// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         spaceId: "yadj1kx9rmg0",
 *         environmentId: "master",
 *         contentTypeId: "blogPost"
 *     }
 */
export interface GetContentTypesRequest {
    /** ID of the space in form of a string */
    spaceId: string;
    /** ID of the environment in form of a string */
    environmentId: string;
    /** ID of the content type in form of a string */
    contentTypeId: string;
}
