// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { EntrySchema } from "../../../types/EntrySchema.js";
import { ListEntriesResponseIncludes } from "./ListEntriesResponseIncludes.js";
import { ListEntriesResponseSys } from "./ListEntriesResponseSys.js";

export const ListEntriesResponse: core.serialization.ObjectSchema<
    serializers.ListEntriesResponse.Raw,
    Contentful.ListEntriesResponse
> = core.serialization.object({
    sys: ListEntriesResponseSys,
    total: core.serialization.number(),
    skip: core.serialization.number(),
    limit: core.serialization.number(),
    items: core.serialization.list(EntrySchema),
    includes: ListEntriesResponseIncludes.optional(),
});

export declare namespace ListEntriesResponse {
    export interface Raw {
        sys: ListEntriesResponseSys.Raw;
        total: number;
        skip: number;
        limit: number;
        items: EntrySchema.Raw[];
        includes?: ListEntriesResponseIncludes.Raw | null;
    }
}
