// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ListEntriesResponseSysType } from "./ListEntriesResponseSysType.js";

export const ListEntriesResponseSys: core.serialization.ObjectSchema<
    serializers.ListEntriesResponseSys.Raw,
    Contentful.ListEntriesResponseSys
> = core.serialization.object({
    type: ListEntriesResponseSysType,
});

export declare namespace ListEntriesResponseSys {
    export interface Raw {
        type: ListEntriesResponseSysType.Raw;
    }
}
