// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListEntriesResponseSysType: core.serialization.Schema<
    serializers.ListEntriesResponseSysType.Raw,
    Contentful.ListEntriesResponseSysType
> = core.serialization.enum_(["Array"]);

export declare namespace ListEntriesResponseSysType {
    export type Raw = "Array";
}
