// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { EntrySchema } from "../../../types/EntrySchema.js";

export const ListEntriesResponseIncludes: core.serialization.ObjectSchema<
    serializers.ListEntriesResponseIncludes.Raw,
    Contentful.ListEntriesResponseIncludes
> = core.serialization.object({
    entry: core.serialization.property("Entry", core.serialization.list(EntrySchema).optional()),
    asset: core.serialization.property("Asset", core.serialization.list(core.serialization.unknown()).optional()),
});

export declare namespace ListEntriesResponseIncludes {
    export interface Raw {
        Entry?: EntrySchema.Raw[] | null;
        Asset?: unknown[] | null;
    }
}
