// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         spaceId: "yadj1kx9rmg0",
 *         environmentId: "master",
 *         entryId: "1nG4SkuMy0WenQUG6z2aEw"
 *     }
 */
export interface GetEntriesRequest {
    /** ID of the space in form of a string */
    spaceId: string;
    /** ID of the environment in form of a string */
    environmentId: string;
    /** ID of the entry in form of a string */
    entryId: string;
}
