// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         spaceId: "yadj1kx9rmg0",
 *         environmentId: "master",
 *         contentType: "blogPost"
 *     }
 */
export interface ListEntriesRequest {
    /** ID of the space in form of a string */
    spaceId: string;
    /** ID of the environment in form of a string */
    environmentId: string;
    /** Filter entries by content type ID */
    contentType?: string;
    /** Enables cursor based pagination */
    cursor?: boolean;
    /** Number of levels of linked resources to include */
    include?: number;
    /** Number of items to skip */
    skip?: number;
    /** Limit number of items returned */
    limit?: number;
}
