// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../../../index.js";

export interface ListEntriesResponseIncludes {
    entry?: Contentful.EntrySchema[];
    asset?: unknown[];
}
