// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../../../index.js";

export interface ListEntriesResponse {
    sys: Contentful.ListEntriesResponseSys;
    total: number;
    skip: number;
    limit: number;
    items: Contentful.EntrySchema[];
    includes?: Contentful.ListEntriesResponseIncludes;
}
