// This file was auto-generated by Fern from our API Definition.

export const ListEntriesResponseSysType = {
    Array: "Array",
} as const;
export type ListEntriesResponseSysType = (typeof ListEntriesResponseSysType)[keyof typeof ListEntriesResponseSysType];
