// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Contentful from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as serializers from "../../../../serialization/index.js";
import * as errors from "../../../../errors/index.js";

export declare namespace ContentTypes {
    export interface Options {
        environment?: core.Supplier<environments.ContentfulEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        spaceId: string;
        environmentId: string;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Content Type related endpoints
 */
export class ContentTypes {
    protected readonly _options: ContentTypes.Options;

    constructor(_options: ContentTypes.Options) {
        this._options = _options;
    }

    /**
     * Get a ContentType by Id
     *
     * @param {Contentful.GetContentTypesRequest} request
     * @param {ContentTypes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contentTypes.get({
     *         spaceId: "yadj1kx9rmg0",
     *         environmentId: "master",
     *         contentTypeId: "blogPost"
     *     })
     */
    public get(
        request: Contentful.GetContentTypesRequest,
        requestOptions?: ContentTypes.RequestOptions,
    ): core.HttpResponsePromise<Contentful.ContentTypeSchema> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Contentful.GetContentTypesRequest,
        requestOptions?: ContentTypes.RequestOptions,
    ): Promise<core.WithRawResponse<Contentful.ContentTypeSchema>> {
        const { spaceId, environmentId, contentTypeId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ContentfulEnvironment.Default,
                `spaces/${encodeURIComponent(this._options.spaceId)}/environments/${encodeURIComponent(this._options.environmentId)}/content_types/${encodeURIComponent(contentTypeId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ContentTypeSchema.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ContentfulError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ContentfulError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ContentfulTimeoutError(
                    "Timeout exceeded when calling GET /spaces/{spaceId}/environments/{environmentId}/content_types/{contentTypeId}.",
                );
            case "unknown":
                throw new errors.ContentfulError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get ContentTypes
     *
     * @param {Contentful.ListContentTypesRequest} request
     * @param {ContentTypes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contentTypes.list({
     *         spaceId: "yadj1kx9rmg0",
     *         environmentId: "master"
     *     })
     */
    public list(
        request: Contentful.ListContentTypesRequest,
        requestOptions?: ContentTypes.RequestOptions,
    ): core.HttpResponsePromise<Contentful.ListContentTypesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Contentful.ListContentTypesRequest,
        requestOptions?: ContentTypes.RequestOptions,
    ): Promise<core.WithRawResponse<Contentful.ListContentTypesResponse>> {
        const { spaceId, environmentId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ContentfulEnvironment.Default,
                `spaces/${encodeURIComponent(this._options.spaceId)}/environments/${encodeURIComponent(this._options.environmentId)}/content_types`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ListContentTypesResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ContentfulError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ContentfulError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ContentfulTimeoutError(
                    "Timeout exceeded when calling GET /spaces/{spaceId}/environments/{environmentId}/content_types.",
                );
            case "unknown":
                throw new errors.ContentfulError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
