// This file was auto-generated by Fern from our API Definition.

export const ContentTypeFieldSchemaItemsLinkType = {
    Asset: "Asset",
    Entry: "Entry",
} as const;
export type ContentTypeFieldSchemaItemsLinkType =
    (typeof ContentTypeFieldSchemaItemsLinkType)[keyof typeof ContentTypeFieldSchemaItemsLinkType];
