// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../index.js";

export interface ContentTypeSchema {
    sys: Contentful.ContentTypeSchemaSys;
    displayField?: string;
    name: string;
    description?: string;
    fields: Contentful.ContentTypeFieldSchema[];
    metadata?: Contentful.ContentTypeSchemaMetadata;
}
