// This file was auto-generated by Fern from our API Definition.

export const ContentTypeFieldTypesSchema = {
    Symbol: "Symbol",
    Text: "Text",
    Number: "Number",
    Integer: "Integer",
    Date: "Date",
    Boolean: "Boolean",
    Location: "Location",
    Object: "Object",
    RichText: "RichText",
    Array: "Array",
    Link: "Link",
    ResourceLink: "ResourceLink",
} as const;
export type ContentTypeFieldTypesSchema =
    (typeof ContentTypeFieldTypesSchema)[keyof typeof ContentTypeFieldTypesSchema];
