// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export interface ContentTypeFieldSchema {
    id: string;
    type: Contentful.ContentTypeFieldTypesSchema;
    name: string;
    localized?: boolean;
    required?: boolean;
    disabled?: boolean;
    omitted?: boolean;
    deleted?: boolean;
    items?: Contentful.ContentTypeFieldSchemaItems;
    validations?: (Contentful.ContentTypeFieldItemValidationSchema | undefined)[];
    allowedResources?: (Contentful.ContentTypeFieldAllowedResourcesSchema | undefined)[];
    linkType?: Contentful.ContentTypeFieldSchemaLinkType;
    defaultValue?: Record<string, unknown>;
}
