// This file was auto-generated by Fern from our API Definition.

export const ContentTypeLinkSchemaSysLinkType = {
    ContentType: "ContentType",
} as const;
export type ContentTypeLinkSchemaSysLinkType =
    (typeof ContentTypeLinkSchemaSysLinkType)[keyof typeof ContentTypeLinkSchemaSysLinkType];
