// This file was auto-generated by Fern from our API Definition.

export const ContentTypeFieldSchemaLinkType = {
    Asset: "Asset",
    Entry: "Entry",
} as const;
export type ContentTypeFieldSchemaLinkType =
    (typeof ContentTypeFieldSchemaLinkType)[keyof typeof ContentTypeFieldSchemaLinkType];
