// This file was auto-generated by Fern from our API Definition.

export const ContentTypeLinkSchemaSysType = {
    Link: "Link",
} as const;
export type ContentTypeLinkSchemaSysType =
    (typeof ContentTypeLinkSchemaSysType)[keyof typeof ContentTypeLinkSchemaSysType];
