// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export interface ContentTypeFieldSchemaItems {
    type: Contentful.ContentTypeFieldTypesSchema;
    linkType?: Contentful.ContentTypeFieldSchemaItemsLinkType;
    validations?: (Contentful.ContentTypeFieldItemValidationSchema | undefined)[];
}
