// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export interface ContentTypeLinkSchemaSys {
    type: Contentful.ContentTypeLinkSchemaSysType;
    linkType: Contentful.ContentTypeLinkSchemaSysLinkType;
    id: string;
}
