// This file was auto-generated by Fern from our API Definition.

export const EntryLinkSchemaSysLinkType = {
    Entry: "Entry",
} as const;
export type EntryLinkSchemaSysLinkType = (typeof EntryLinkSchemaSysLinkType)[keyof typeof EntryLinkSchemaSysLinkType];
