// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export interface EntryFieldsSchemaValueValueContentContentItem {
    nodeType: Contentful.EntryFieldsSchemaValueValueContentContentItemNodeType;
    data: Record<string, unknown>;
    content: Contentful.EntryFieldsSchemaValueValueContentContentItemContentItem[];
}
