// This file was auto-generated by Fern from our API Definition.

export const EntrySchemaSysFieldStatusValue = {
    Draft: "draft",
    Changed: "changed",
    Published: "published",
} as const;
export type EntrySchemaSysFieldStatusValue =
    (typeof EntrySchemaSysFieldStatusValue)[keyof typeof EntrySchemaSysFieldStatusValue];
