// This file was auto-generated by Fern from our API Definition.

export const EntryLinkSchemaSysType = {
    Link: "Link",
} as const;
export type EntryLinkSchemaSysType = (typeof EntryLinkSchemaSysType)[keyof typeof EntryLinkSchemaSysType];
