// This file was auto-generated by Fern from our API Definition.

export const EntryFieldsSchemaValueValueContentContentItemNodeType = {
    Paragraph: "paragraph",
} as const;
export type EntryFieldsSchemaValueValueContentContentItemNodeType =
    (typeof EntryFieldsSchemaValueValueContentContentItemNodeType)[keyof typeof EntryFieldsSchemaValueValueContentContentItemNodeType];
