// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../index.js";

export interface EntryFieldsSchemaValueValueFiveItemSys {
    type: Contentful.EntryFieldsSchemaValueValueFiveItemSysType;
    linkType: Contentful.EntryFieldsSchemaValueValueFiveItemSysLinkType;
    id: string;
}
