// This file was auto-generated by Fern from our API Definition.

export const EntryFieldsSchemaValueValueContentContentItemContentItemNodeType = {
    Text: "text",
} as const;
export type EntryFieldsSchemaValueValueContentContentItemContentItemNodeType =
    (typeof EntryFieldsSchemaValueValueContentContentItemContentItemNodeType)[keyof typeof EntryFieldsSchemaValueValueContentContentItemContentItemNodeType];
