// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../index.js";

export interface EntrySchema {
    metadata: Contentful.EntrySchemaMetadata;
    sys: Contentful.EntrySchemaSys;
    fields: Contentful.EntryFieldsSchema;
}
