// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../index.js";

export interface EntrySchemaSys {
    space: Contentful.SpaceLinkSchema;
    id: string;
    type: string;
    createdAt: Contentful.IsoDateTimeSchema;
    updatedAt: Contentful.IsoDateTimeSchema;
    environment: Contentful.EnvironmentLinkSchema;
    publishedVersion?: number;
    publishedAt?: Contentful.IsoDateTimeSchema;
    firstPublishedAt?: Contentful.IsoDateTimeSchema;
    createdBy?: Contentful.UserLinkSchema;
    updatedBy?: Contentful.UserLinkSchema;
    publishedCounter?: number;
    version?: number;
    publishedBy?: Contentful.UserLinkSchema;
    fieldStatus?: Contentful.EntrySchemaSysFieldStatus;
    automationTags?: Contentful.TagLinkSchema[];
    contentType: Contentful.ContentTypeLinkSchema;
    urn?: string;
}
