// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export type EntryFieldsSchemaValueValue =
    | string
    | number
    | boolean
    | string[]
    | Contentful.EntryLinkSchema[]
    | Contentful.EntryFieldsSchemaValueValueFiveItem[]
    | Contentful.EntryLinkSchema
    | Contentful.EntryFieldsSchemaValueValueContent
    | Contentful.EntryFieldsSchemaValueValueLat
    | Record<string, unknown>
    | unknown;
