// This file was auto-generated by Fern from our API Definition.

export const EntryFieldsSchemaValueValueContentNodeType = {
    Document: "document",
} as const;
export type EntryFieldsSchemaValueValueContentNodeType =
    (typeof EntryFieldsSchemaValueValueContentNodeType)[keyof typeof EntryFieldsSchemaValueValueContentNodeType];
