// This file was auto-generated by Fern from our API Definition.

export const EntryFieldsSchemaValueValueFiveItemSysLinkType = {
    Asset: "Asset",
} as const;
export type EntryFieldsSchemaValueValueFiveItemSysLinkType =
    (typeof EntryFieldsSchemaValueValueFiveItemSysLinkType)[keyof typeof EntryFieldsSchemaValueValueFiveItemSysLinkType];
