// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../index.js";

export interface EntryFieldsSchemaValueValueContent {
    nodeType: Contentful.EntryFieldsSchemaValueValueContentNodeType;
    data: Record<string, unknown>;
    content: Contentful.EntryFieldsSchemaValueValueContentContentItem[];
}
