// This file was auto-generated by Fern from our API Definition.

export const EntryFieldsSchemaValueValueFiveItemSysType = {
    Link: "Link",
} as const;
export type EntryFieldsSchemaValueValueFiveItemSysType =
    (typeof EntryFieldsSchemaValueValueFiveItemSysType)[keyof typeof EntryFieldsSchemaValueValueFiveItemSysType];
