// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export interface EntryLinkSchemaSys {
    type: Contentful.EntryLinkSchemaSysType;
    linkType: Contentful.EntryLinkSchemaSysLinkType;
    id: string;
}
