// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export type EntryFieldsSchema = Record<string, Record<string, Contentful.EntryFieldsSchemaValueValue>>;
