// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export interface EnvironmentLinkSchemaSys {
    type: Contentful.EnvironmentLinkSchemaSysType;
    linkType: Contentful.EnvironmentLinkSchemaSysLinkType;
    id: string;
}
