// This file was auto-generated by Fern from our API Definition.

export const EnvironmentLinkSchemaSysType = {
    Link: "Link",
} as const;
export type EnvironmentLinkSchemaSysType =
    (typeof EnvironmentLinkSchemaSysType)[keyof typeof EnvironmentLinkSchemaSysType];
