// This file was auto-generated by Fern from our API Definition.

export const EnvironmentLinkSchemaSysLinkType = {
    Environment: "Environment",
} as const;
export type EnvironmentLinkSchemaSysLinkType =
    (typeof EnvironmentLinkSchemaSysLinkType)[keyof typeof EnvironmentLinkSchemaSysLinkType];
