// This file was auto-generated by Fern from our API Definition.

export const SpaceLinkSchemaSysLinkType = {
    Space: "Space",
} as const;
export type SpaceLinkSchemaSysLinkType = (typeof SpaceLinkSchemaSysLinkType)[keyof typeof SpaceLinkSchemaSysLinkType];
