// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../index.js";

export interface SpaceLinkSchemaSys {
    type: Contentful.SpaceLinkSchemaSysType;
    linkType: Contentful.SpaceLinkSchemaSysLinkType;
    id: string;
}
