// This file was auto-generated by Fern from our API Definition.

export const SpaceLinkSchemaSysType = {
    Link: "Link",
} as const;
export type SpaceLinkSchemaSysType = (typeof SpaceLinkSchemaSysType)[keyof typeof SpaceLinkSchemaSysType];
