// This file was auto-generated by Fern from our API Definition.

export const TagLinkSchemaSysType = {
    Link: "Link",
} as const;
export type TagLinkSchemaSysType = (typeof TagLinkSchemaSysType)[keyof typeof TagLinkSchemaSysType];
