// This file was auto-generated by Fern from our API Definition.

export const TagLinkSchemaSysLinkType = {
    Tag: "Tag",
} as const;
export type TagLinkSchemaSysLinkType = (typeof TagLinkSchemaSysLinkType)[keyof typeof TagLinkSchemaSysLinkType];
