// This file was auto-generated by Fern from our API Definition.

export const TaxonomyConceptLinkSchemaSysType = {
    Link: "Link",
} as const;
export type TaxonomyConceptLinkSchemaSysType =
    (typeof TaxonomyConceptLinkSchemaSysType)[keyof typeof TaxonomyConceptLinkSchemaSysType];
