// This file was auto-generated by Fern from our API Definition.

import * as Contentful from "../index.js";

export interface TaxonomyConceptLinkSchemaSys {
    type: Contentful.TaxonomyConceptLinkSchemaSysType;
    linkType: Contentful.TaxonomyConceptLinkSchemaSysLinkType;
    id: string;
}
