// This file was auto-generated by Fern from our API Definition.

export const TaxonomyConceptLinkSchemaSysLinkType = {
    TaxonomyConcept: "TaxonomyConcept",
} as const;
export type TaxonomyConceptLinkSchemaSysLinkType =
    (typeof TaxonomyConceptLinkSchemaSysLinkType)[keyof typeof TaxonomyConceptLinkSchemaSysLinkType];
