// This file was auto-generated by Fern from our API Definition.

export const UserLinkSchemaSysLinkType = {
    User: "User",
} as const;
export type UserLinkSchemaSysLinkType = (typeof UserLinkSchemaSysLinkType)[keyof typeof UserLinkSchemaSysLinkType];
