// This file was auto-generated by Fern from our API Definition.

export const UserLinkSchemaSysType = {
    Link: "Link",
} as const;
export type UserLinkSchemaSysType = (typeof UserLinkSchemaSysType)[keyof typeof UserLinkSchemaSysType];
