// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../index.js";

export interface UserLinkSchemaSys {
    type: Contentful.UserLinkSchemaSysType;
    linkType: Contentful.UserLinkSchemaSysLinkType;
    id: string;
}
