// This file was auto-generated by Fern from our API Definition.

export const ListContentTypesResponseSysType = {
    Array: "Array",
} as const;
export type ListContentTypesResponseSysType =
    (typeof ListContentTypesResponseSysType)[keyof typeof ListContentTypesResponseSysType];
