// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../index.js";

export interface ListContentTypesResponse {
    sys: Contentful.ListContentTypesResponseSys;
    total: number;
    skip: number;
    limit: number;
    items: Contentful.ContentTypeSchema[];
    includes?: Contentful.ListContentTypesResponseIncludes;
}
