// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const ContentTypeLinkSchemaSysLinkType: core.serialization.Schema<
    serializers.ContentTypeLinkSchemaSysLinkType.Raw,
    Contentful.ContentTypeLinkSchemaSysLinkType
> = core.serialization.enum_(["ContentType"]);

export declare namespace ContentTypeLinkSchemaSysLinkType {
    export type Raw = "ContentType";
}
