// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { ContentTypeFieldTypesSchema } from "./ContentTypeFieldTypesSchema.js";
import { ContentTypeFieldSchemaItems } from "./ContentTypeFieldSchemaItems.js";
import { ContentTypeFieldItemValidationSchema } from "./ContentTypeFieldItemValidationSchema.js";
import { ContentTypeFieldAllowedResourcesSchema } from "./ContentTypeFieldAllowedResourcesSchema.js";
import { ContentTypeFieldSchemaLinkType } from "./ContentTypeFieldSchemaLinkType.js";

export const ContentTypeFieldSchema: core.serialization.ObjectSchema<
    serializers.ContentTypeFieldSchema.Raw,
    Contentful.ContentTypeFieldSchema
> = core.serialization.object({
    id: core.serialization.string(),
    type: ContentTypeFieldTypesSchema,
    name: core.serialization.string(),
    localized: core.serialization.boolean().optional(),
    required: core.serialization.boolean().optional(),
    disabled: core.serialization.boolean().optional(),
    omitted: core.serialization.boolean().optional(),
    deleted: core.serialization.boolean().optional(),
    items: ContentTypeFieldSchemaItems.optional(),
    validations: core.serialization.list(ContentTypeFieldItemValidationSchema).optional(),
    allowedResources: core.serialization.list(ContentTypeFieldAllowedResourcesSchema).optional(),
    linkType: ContentTypeFieldSchemaLinkType.optional(),
    defaultValue: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace ContentTypeFieldSchema {
    export interface Raw {
        id: string;
        type: ContentTypeFieldTypesSchema.Raw;
        name: string;
        localized?: boolean | null;
        required?: boolean | null;
        disabled?: boolean | null;
        omitted?: boolean | null;
        deleted?: boolean | null;
        items?: ContentTypeFieldSchemaItems.Raw | null;
        validations?: (ContentTypeFieldItemValidationSchema.Raw | undefined)[] | null;
        allowedResources?: (ContentTypeFieldAllowedResourcesSchema.Raw | undefined)[] | null;
        linkType?: ContentTypeFieldSchemaLinkType.Raw | null;
        defaultValue?: Record<string, unknown> | null;
    }
}
