// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ContentTypeFieldItemValidationSchema: core.serialization.Schema<
    serializers.ContentTypeFieldItemValidationSchema.Raw,
    Contentful.ContentTypeFieldItemValidationSchema
> = core.serialization.unknown();

export declare namespace ContentTypeFieldItemValidationSchema {
    export type Raw = unknown;
}
