// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { ContentTypeSchemaSys } from "./ContentTypeSchemaSys.js";
import { ContentTypeFieldSchema } from "./ContentTypeFieldSchema.js";
import { ContentTypeSchemaMetadata } from "./ContentTypeSchemaMetadata.js";

export const ContentTypeSchema: core.serialization.ObjectSchema<
    serializers.ContentTypeSchema.Raw,
    Contentful.ContentTypeSchema
> = core.serialization.object({
    sys: ContentTypeSchemaSys,
    displayField: core.serialization.string().optional(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    fields: core.serialization.list(ContentTypeFieldSchema),
    metadata: ContentTypeSchemaMetadata.optional(),
});

export declare namespace ContentTypeSchema {
    export interface Raw {
        sys: ContentTypeSchemaSys.Raw;
        displayField?: string | null;
        name: string;
        description?: string | null;
        fields: ContentTypeFieldSchema.Raw[];
        metadata?: ContentTypeSchemaMetadata.Raw | null;
    }
}
