// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { ContentTypeLinkSchemaSysType } from "./ContentTypeLinkSchemaSysType.js";
import { ContentTypeLinkSchemaSysLinkType } from "./ContentTypeLinkSchemaSysLinkType.js";

export const ContentTypeLinkSchemaSys: core.serialization.ObjectSchema<
    serializers.ContentTypeLinkSchemaSys.Raw,
    Contentful.ContentTypeLinkSchemaSys
> = core.serialization.object({
    type: ContentTypeLinkSchemaSysType,
    linkType: ContentTypeLinkSchemaSysLinkType,
    id: core.serialization.string(),
});

export declare namespace ContentTypeLinkSchemaSys {
    export interface Raw {
        type: ContentTypeLinkSchemaSysType.Raw;
        linkType: ContentTypeLinkSchemaSysLinkType.Raw;
        id: string;
    }
}
