// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const ContentTypeFieldSchemaItemsLinkType: core.serialization.Schema<
    serializers.ContentTypeFieldSchemaItemsLinkType.Raw,
    Contentful.ContentTypeFieldSchemaItemsLinkType
> = core.serialization.enum_(["Asset", "Entry"]);

export declare namespace ContentTypeFieldSchemaItemsLinkType {
    export type Raw = "Asset" | "Entry";
}
