// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ContentTypeLinkSchemaSys } from "./ContentTypeLinkSchemaSys.js";

export const ContentTypeLinkSchema: core.serialization.ObjectSchema<
    serializers.ContentTypeLinkSchema.Raw,
    Contentful.ContentTypeLinkSchema
> = core.serialization.object({
    sys: ContentTypeLinkSchemaSys,
});

export declare namespace ContentTypeLinkSchema {
    export interface Raw {
        sys: ContentTypeLinkSchemaSys.Raw;
    }
}
