// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ContentTypeLinkSchema } from "./ContentTypeLinkSchema.js";
import { EnvironmentLinkSchema } from "./EnvironmentLinkSchema.js";
import { IsoDateTimeSchema } from "./IsoDateTimeSchema.js";
import { SpaceLinkSchema } from "./SpaceLinkSchema.js";
import { UserLinkSchema } from "./UserLinkSchema.js";

export const ContentTypeSchemaSys: core.serialization.ObjectSchema<
    serializers.ContentTypeSchemaSys.Raw,
    Contentful.ContentTypeSchemaSys
> = core.serialization.object({
    space: SpaceLinkSchema,
    id: core.serialization.string(),
    type: ContentTypeLinkSchema,
    createdAt: IsoDateTimeSchema,
    updatedAt: IsoDateTimeSchema,
    environment: EnvironmentLinkSchema,
    publishedVersion: core.serialization.number().optional(),
    publishedAt: IsoDateTimeSchema.optional(),
    firstPublishedAt: IsoDateTimeSchema.optional(),
    createdBy: UserLinkSchema,
    updatedBy: UserLinkSchema,
    publishedCounter: core.serialization.number(),
    version: core.serialization.number(),
    publishedBy: UserLinkSchema.optional(),
});

export declare namespace ContentTypeSchemaSys {
    export interface Raw {
        space: SpaceLinkSchema.Raw;
        id: string;
        type: ContentTypeLinkSchema.Raw;
        createdAt: IsoDateTimeSchema.Raw;
        updatedAt: IsoDateTimeSchema.Raw;
        environment: EnvironmentLinkSchema.Raw;
        publishedVersion?: number | null;
        publishedAt?: IsoDateTimeSchema.Raw | null;
        firstPublishedAt?: IsoDateTimeSchema.Raw | null;
        createdBy: UserLinkSchema.Raw;
        updatedBy: UserLinkSchema.Raw;
        publishedCounter: number;
        version: number;
        publishedBy?: UserLinkSchema.Raw | null;
    }
}
