// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ContentTypeFieldSchemaLinkType: core.serialization.Schema<
    serializers.ContentTypeFieldSchemaLinkType.Raw,
    Contentful.ContentTypeFieldSchemaLinkType
> = core.serialization.enum_(["Asset", "Entry"]);

export declare namespace ContentTypeFieldSchemaLinkType {
    export type Raw = "Asset" | "Entry";
}
