// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const ContentTypeFieldAllowedResourcesSchema: core.serialization.Schema<
    serializers.ContentTypeFieldAllowedResourcesSchema.Raw,
    Contentful.ContentTypeFieldAllowedResourcesSchema
> = core.serialization.unknown();

export declare namespace ContentTypeFieldAllowedResourcesSchema {
    export type Raw = unknown;
}
