// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { ContentTypeFieldTypesSchema } from "./ContentTypeFieldTypesSchema.js";
import { ContentTypeFieldSchemaItemsLinkType } from "./ContentTypeFieldSchemaItemsLinkType.js";
import { ContentTypeFieldItemValidationSchema } from "./ContentTypeFieldItemValidationSchema.js";

export const ContentTypeFieldSchemaItems: core.serialization.ObjectSchema<
    serializers.ContentTypeFieldSchemaItems.Raw,
    Contentful.ContentTypeFieldSchemaItems
> = core.serialization.object({
    type: ContentTypeFieldTypesSchema,
    linkType: ContentTypeFieldSchemaItemsLinkType.optional(),
    validations: core.serialization.list(ContentTypeFieldItemValidationSchema).optional(),
});

export declare namespace ContentTypeFieldSchemaItems {
    export interface Raw {
        type: ContentTypeFieldTypesSchema.Raw;
        linkType?: ContentTypeFieldSchemaItemsLinkType.Raw | null;
        validations?: (ContentTypeFieldItemValidationSchema.Raw | undefined)[] | null;
    }
}
