// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { TaxonomyConceptLinkSchema } from "./TaxonomyConceptLinkSchema.js";

export const ContentTypeSchemaMetadata: core.serialization.ObjectSchema<
    serializers.ContentTypeSchemaMetadata.Raw,
    Contentful.ContentTypeSchemaMetadata
> = core.serialization.object({
    annotations: core.serialization.list(core.serialization.unknown()).optional(),
    taxonomy: core.serialization.list(TaxonomyConceptLinkSchema).optional(),
});

export declare namespace ContentTypeSchemaMetadata {
    export interface Raw {
        annotations?: unknown[] | null;
        taxonomy?: TaxonomyConceptLinkSchema.Raw[] | null;
    }
}
