// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const ContentTypeLinkSchemaSysType: core.serialization.Schema<
    serializers.ContentTypeLinkSchemaSysType.Raw,
    Contentful.ContentTypeLinkSchemaSysType
> = core.serialization.enum_(["Link"]);

export declare namespace ContentTypeLinkSchemaSysType {
    export type Raw = "Link";
}
