// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const ContentTypeFieldTypesSchema: core.serialization.Schema<
    serializers.ContentTypeFieldTypesSchema.Raw,
    Contentful.ContentTypeFieldTypesSchema
> = core.serialization.enum_([
    "Symbol",
    "Text",
    "Number",
    "Integer",
    "Date",
    "Boolean",
    "Location",
    "Object",
    "RichText",
    "Array",
    "Link",
    "ResourceLink",
]);

export declare namespace ContentTypeFieldTypesSchema {
    export type Raw =
        | "Symbol"
        | "Text"
        | "Number"
        | "Integer"
        | "Date"
        | "Boolean"
        | "Location"
        | "Object"
        | "RichText"
        | "Array"
        | "Link"
        | "ResourceLink";
}
