// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { EntryFieldsSchemaValueValueContentContentItemContentItemNodeType } from "./EntryFieldsSchemaValueValueContentContentItemContentItemNodeType.js";
import { EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem } from "./EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem.js";

export const EntryFieldsSchemaValueValueContentContentItemContentItem: core.serialization.ObjectSchema<
    serializers.EntryFieldsSchemaValueValueContentContentItemContentItem.Raw,
    Contentful.EntryFieldsSchemaValueValueContentContentItemContentItem
> = core.serialization.object({
    nodeType: EntryFieldsSchemaValueValueContentContentItemContentItemNodeType,
    value: core.serialization.string(),
    marks: core.serialization.list(EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem),
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace EntryFieldsSchemaValueValueContentContentItemContentItem {
    export interface Raw {
        nodeType: EntryFieldsSchemaValueValueContentContentItemContentItemNodeType.Raw;
        value: string;
        marks: EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem.Raw[];
        data: Record<string, unknown>;
    }
}
