// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EntryFieldsSchemaValueValueFiveItemSysLinkType: core.serialization.Schema<
    serializers.EntryFieldsSchemaValueValueFiveItemSysLinkType.Raw,
    Contentful.EntryFieldsSchemaValueValueFiveItemSysLinkType
> = core.serialization.enum_(["Asset"]);

export declare namespace EntryFieldsSchemaValueValueFiveItemSysLinkType {
    export type Raw = "Asset";
}
