// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntryFieldsSchemaValueValueFiveItemSysLinkType } from "./EntryFieldsSchemaValueValueFiveItemSysLinkType.js";
import { EntryFieldsSchemaValueValueFiveItemSysType } from "./EntryFieldsSchemaValueValueFiveItemSysType.js";

export const EntryFieldsSchemaValueValueFiveItemSys: core.serialization.ObjectSchema<
    serializers.EntryFieldsSchemaValueValueFiveItemSys.Raw,
    Contentful.EntryFieldsSchemaValueValueFiveItemSys
> = core.serialization.object({
    type: EntryFieldsSchemaValueValueFiveItemSysType,
    linkType: EntryFieldsSchemaValueValueFiveItemSysLinkType,
    id: core.serialization.string(),
});

export declare namespace EntryFieldsSchemaValueValueFiveItemSys {
    export interface Raw {
        type: EntryFieldsSchemaValueValueFiveItemSysType.Raw;
        linkType: EntryFieldsSchemaValueValueFiveItemSysLinkType.Raw;
        id: string;
    }
}
