// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntryFieldsSchemaValueValueFiveItemSys } from "./EntryFieldsSchemaValueValueFiveItemSys.js";

export const EntryFieldsSchemaValueValueFiveItem: core.serialization.ObjectSchema<
    serializers.EntryFieldsSchemaValueValueFiveItem.Raw,
    Contentful.EntryFieldsSchemaValueValueFiveItem
> = core.serialization.object({
    sys: EntryFieldsSchemaValueValueFiveItemSys,
});

export declare namespace EntryFieldsSchemaValueValueFiveItem {
    export interface Raw {
        sys: EntryFieldsSchemaValueValueFiveItemSys.Raw;
    }
}
