// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem: core.serialization.ObjectSchema<
    serializers.EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem.Raw,
    Contentful.EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem
> = core.serialization
    .object({
        type: core.serialization.string(),
    })
    .passthrough();

export declare namespace EntryFieldsSchemaValueValueContentContentItemContentItemMarksItem {
    export interface Raw {
        type: string;
        [key: string]: any;
    }
}
