// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { TagLinkSchema } from "./TagLinkSchema.js";
import { TaxonomyConceptLinkSchema } from "./TaxonomyConceptLinkSchema.js";

export const EntrySchemaMetadata: core.serialization.ObjectSchema<
    serializers.EntrySchemaMetadata.Raw,
    Contentful.EntrySchemaMetadata
> = core.serialization.object({
    tags: core.serialization.list(TagLinkSchema),
    concepts: core.serialization.list(TaxonomyConceptLinkSchema).optional(),
});

export declare namespace EntrySchemaMetadata {
    export interface Raw {
        tags: TagLinkSchema.Raw[];
        concepts?: TaxonomyConceptLinkSchema.Raw[] | null;
    }
}
