// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntryFieldsSchemaValueValueContentContentItemContentItem } from "./EntryFieldsSchemaValueValueContentContentItemContentItem.js";
import { EntryFieldsSchemaValueValueContentContentItemNodeType } from "./EntryFieldsSchemaValueValueContentContentItemNodeType.js";

export const EntryFieldsSchemaValueValueContentContentItem: core.serialization.ObjectSchema<
    serializers.EntryFieldsSchemaValueValueContentContentItem.Raw,
    Contentful.EntryFieldsSchemaValueValueContentContentItem
> = core.serialization.object({
    nodeType: EntryFieldsSchemaValueValueContentContentItemNodeType,
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    content: core.serialization.list(EntryFieldsSchemaValueValueContentContentItemContentItem),
});

export declare namespace EntryFieldsSchemaValueValueContentContentItem {
    export interface Raw {
        nodeType: EntryFieldsSchemaValueValueContentContentItemNodeType.Raw;
        data: Record<string, unknown>;
        content: EntryFieldsSchemaValueValueContentContentItemContentItem.Raw[];
    }
}
