// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EntryFieldsSchemaValueValueContentNodeType: core.serialization.Schema<
    serializers.EntryFieldsSchemaValueValueContentNodeType.Raw,
    Contentful.EntryFieldsSchemaValueValueContentNodeType
> = core.serialization.enum_(["document"]);

export declare namespace EntryFieldsSchemaValueValueContentNodeType {
    export type Raw = "document";
}
