// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const EntryLinkSchemaSysType: core.serialization.Schema<
    serializers.EntryLinkSchemaSysType.Raw,
    Contentful.EntryLinkSchemaSysType
> = core.serialization.enum_(["Link"]);

export declare namespace EntryLinkSchemaSysType {
    export type Raw = "Link";
}
