// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntrySchemaSysFieldStatusValue } from "./EntrySchemaSysFieldStatusValue.js";

export const EntrySchemaSysFieldStatus: core.serialization.ObjectSchema<
    serializers.EntrySchemaSysFieldStatus.Raw,
    Contentful.EntrySchemaSysFieldStatus
> = core.serialization.object({
    properties: core.serialization.property(
        "*",
        core.serialization.record(core.serialization.string(), EntrySchemaSysFieldStatusValue),
    ),
});

export declare namespace EntrySchemaSysFieldStatus {
    export interface Raw {
        "*": Record<string, EntrySchemaSysFieldStatusValue.Raw>;
    }
}
