// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EntryFieldsSchemaValueValueContentContentItemContentItemNodeType: core.serialization.Schema<
    serializers.EntryFieldsSchemaValueValueContentContentItemContentItemNodeType.Raw,
    Contentful.EntryFieldsSchemaValueValueContentContentItemContentItemNodeType
> = core.serialization.enum_(["text"]);

export declare namespace EntryFieldsSchemaValueValueContentContentItemContentItemNodeType {
    export type Raw = "text";
}
