// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EntrySchemaSysFieldStatusValue: core.serialization.Schema<
    serializers.EntrySchemaSysFieldStatusValue.Raw,
    Contentful.EntrySchemaSysFieldStatusValue
> = core.serialization.enum_(["draft", "changed", "published"]);

export declare namespace EntrySchemaSysFieldStatusValue {
    export type Raw = "draft" | "changed" | "published";
}
