// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EntryFieldsSchemaValueValueFiveItemSysType: core.serialization.Schema<
    serializers.EntryFieldsSchemaValueValueFiveItemSysType.Raw,
    Contentful.EntryFieldsSchemaValueValueFiveItemSysType
> = core.serialization.enum_(["Link"]);

export declare namespace EntryFieldsSchemaValueValueFiveItemSysType {
    export type Raw = "Link";
}
