// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { EntryFieldsSchemaValueValueContentNodeType } from "./EntryFieldsSchemaValueValueContentNodeType.js";
import { EntryFieldsSchemaValueValueContentContentItem } from "./EntryFieldsSchemaValueValueContentContentItem.js";

export const EntryFieldsSchemaValueValueContent: core.serialization.ObjectSchema<
    serializers.EntryFieldsSchemaValueValueContent.Raw,
    Contentful.EntryFieldsSchemaValueValueContent
> = core.serialization.object({
    nodeType: EntryFieldsSchemaValueValueContentNodeType,
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    content: core.serialization.list(EntryFieldsSchemaValueValueContentContentItem),
});

export declare namespace EntryFieldsSchemaValueValueContent {
    export interface Raw {
        nodeType: EntryFieldsSchemaValueValueContentNodeType.Raw;
        data: Record<string, unknown>;
        content: EntryFieldsSchemaValueValueContentContentItem.Raw[];
    }
}
