// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { EntryLinkSchema } from "./EntryLinkSchema.js";
import { EntryFieldsSchemaValueValueFiveItem } from "./EntryFieldsSchemaValueValueFiveItem.js";
import { EntryFieldsSchemaValueValueContent } from "./EntryFieldsSchemaValueValueContent.js";
import { EntryFieldsSchemaValueValueLat } from "./EntryFieldsSchemaValueValueLat.js";

export const EntryFieldsSchemaValueValue: core.serialization.Schema<
    serializers.EntryFieldsSchemaValueValue.Raw,
    Contentful.EntryFieldsSchemaValueValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.boolean(),
    core.serialization.list(core.serialization.string()),
    core.serialization.list(EntryLinkSchema),
    core.serialization.list(EntryFieldsSchemaValueValueFiveItem),
    EntryLinkSchema,
    EntryFieldsSchemaValueValueContent,
    EntryFieldsSchemaValueValueLat,
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    core.serialization.unknown(),
]);

export declare namespace EntryFieldsSchemaValueValue {
    export type Raw =
        | string
        | number
        | boolean
        | string[]
        | EntryLinkSchema.Raw[]
        | EntryFieldsSchemaValueValueFiveItem.Raw[]
        | EntryLinkSchema.Raw
        | EntryFieldsSchemaValueValueContent.Raw
        | EntryFieldsSchemaValueValueLat.Raw
        | Record<string, unknown>
        | unknown;
}
