// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntryLinkSchemaSysLinkType } from "./EntryLinkSchemaSysLinkType.js";
import { EntryLinkSchemaSysType } from "./EntryLinkSchemaSysType.js";

export const EntryLinkSchemaSys: core.serialization.ObjectSchema<
    serializers.EntryLinkSchemaSys.Raw,
    Contentful.EntryLinkSchemaSys
> = core.serialization.object({
    type: EntryLinkSchemaSysType,
    linkType: EntryLinkSchemaSysLinkType,
    id: core.serialization.string(),
});

export declare namespace EntryLinkSchemaSys {
    export interface Raw {
        type: EntryLinkSchemaSysType.Raw;
        linkType: EntryLinkSchemaSysLinkType.Raw;
        id: string;
    }
}
