// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { SpaceLinkSchema } from "./SpaceLinkSchema.js";
import { IsoDateTimeSchema } from "./IsoDateTimeSchema.js";
import { EnvironmentLinkSchema } from "./EnvironmentLinkSchema.js";
import { UserLinkSchema } from "./UserLinkSchema.js";
import { EntrySchemaSysFieldStatus } from "./EntrySchemaSysFieldStatus.js";
import { TagLinkSchema } from "./TagLinkSchema.js";
import { ContentTypeLinkSchema } from "./ContentTypeLinkSchema.js";

export const EntrySchemaSys: core.serialization.ObjectSchema<
    serializers.EntrySchemaSys.Raw,
    Contentful.EntrySchemaSys
> = core.serialization.object({
    space: SpaceLinkSchema,
    id: core.serialization.string(),
    type: core.serialization.string(),
    createdAt: IsoDateTimeSchema,
    updatedAt: IsoDateTimeSchema,
    environment: EnvironmentLinkSchema,
    publishedVersion: core.serialization.number().optional(),
    publishedAt: IsoDateTimeSchema.optional(),
    firstPublishedAt: IsoDateTimeSchema.optional(),
    createdBy: UserLinkSchema.optional(),
    updatedBy: UserLinkSchema.optional(),
    publishedCounter: core.serialization.number().optional(),
    version: core.serialization.number().optional(),
    publishedBy: UserLinkSchema.optional(),
    fieldStatus: EntrySchemaSysFieldStatus.optional(),
    automationTags: core.serialization.list(TagLinkSchema).optional(),
    contentType: ContentTypeLinkSchema,
    urn: core.serialization.string().optional(),
});

export declare namespace EntrySchemaSys {
    export interface Raw {
        space: SpaceLinkSchema.Raw;
        id: string;
        type: string;
        createdAt: IsoDateTimeSchema.Raw;
        updatedAt: IsoDateTimeSchema.Raw;
        environment: EnvironmentLinkSchema.Raw;
        publishedVersion?: number | null;
        publishedAt?: IsoDateTimeSchema.Raw | null;
        firstPublishedAt?: IsoDateTimeSchema.Raw | null;
        createdBy?: UserLinkSchema.Raw | null;
        updatedBy?: UserLinkSchema.Raw | null;
        publishedCounter?: number | null;
        version?: number | null;
        publishedBy?: UserLinkSchema.Raw | null;
        fieldStatus?: EntrySchemaSysFieldStatus.Raw | null;
        automationTags?: TagLinkSchema.Raw[] | null;
        contentType: ContentTypeLinkSchema.Raw;
        urn?: string | null;
    }
}
