// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const EntryLinkSchemaSysLinkType: core.serialization.Schema<
    serializers.EntryLinkSchemaSysLinkType.Raw,
    Contentful.EntryLinkSchemaSysLinkType
> = core.serialization.enum_(["Entry"]);

export declare namespace EntryLinkSchemaSysLinkType {
    export type Raw = "Entry";
}
