// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntryLinkSchemaSys } from "./EntryLinkSchemaSys.js";

export const EntryLinkSchema: core.serialization.ObjectSchema<
    serializers.EntryLinkSchema.Raw,
    Contentful.EntryLinkSchema
> = core.serialization.object({
    sys: EntryLinkSchemaSys,
});

export declare namespace EntryLinkSchema {
    export interface Raw {
        sys: EntryLinkSchemaSys.Raw;
    }
}
