// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntryFieldsSchema } from "./EntryFieldsSchema.js";
import { EntrySchemaMetadata } from "./EntrySchemaMetadata.js";
import { EntrySchemaSys } from "./EntrySchemaSys.js";

export const EntrySchema: core.serialization.ObjectSchema<serializers.EntrySchema.Raw, Contentful.EntrySchema> =
    core.serialization.object({
        metadata: EntrySchemaMetadata,
        sys: EntrySchemaSys,
        fields: EntryFieldsSchema,
    });

export declare namespace EntrySchema {
    export interface Raw {
        metadata: EntrySchemaMetadata.Raw;
        sys: EntrySchemaSys.Raw;
        fields: EntryFieldsSchema.Raw;
    }
}
