// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EntryFieldsSchemaValueValue } from "./EntryFieldsSchemaValueValue.js";

export const EntryFieldsSchema: core.serialization.Schema<
    serializers.EntryFieldsSchema.Raw,
    Contentful.EntryFieldsSchema
> = core.serialization.record(
    core.serialization.string(),
    core.serialization.record(core.serialization.string(), EntryFieldsSchemaValueValue),
);

export declare namespace EntryFieldsSchema {
    export type Raw = Record<string, Record<string, EntryFieldsSchemaValueValue.Raw>>;
}
