// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const EntryFieldsSchemaValueValueLat: core.serialization.ObjectSchema<
    serializers.EntryFieldsSchemaValueValueLat.Raw,
    Contentful.EntryFieldsSchemaValueValueLat
> = core.serialization.object({
    lon: core.serialization.number(),
    lat: core.serialization.number(),
});

export declare namespace EntryFieldsSchemaValueValueLat {
    export interface Raw {
        lon: number;
        lat: number;
    }
}
