// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EntryFieldsSchemaValueValueContentContentItemNodeType: core.serialization.Schema<
    serializers.EntryFieldsSchemaValueValueContentContentItemNodeType.Raw,
    Contentful.EntryFieldsSchemaValueValueContentContentItemNodeType
> = core.serialization.enum_(["paragraph"]);

export declare namespace EntryFieldsSchemaValueValueContentContentItemNodeType {
    export type Raw = "paragraph";
}
