// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const EnvironmentLinkSchemaSysLinkType: core.serialization.Schema<
    serializers.EnvironmentLinkSchemaSysLinkType.Raw,
    Contentful.EnvironmentLinkSchemaSysLinkType
> = core.serialization.enum_(["Environment"]);

export declare namespace EnvironmentLinkSchemaSysLinkType {
    export type Raw = "Environment";
}
