// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const EnvironmentLinkSchemaSysType: core.serialization.Schema<
    serializers.EnvironmentLinkSchemaSysType.Raw,
    Contentful.EnvironmentLinkSchemaSysType
> = core.serialization.enum_(["Link"]);

export declare namespace EnvironmentLinkSchemaSysType {
    export type Raw = "Link";
}
