// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EnvironmentLinkSchemaSysLinkType } from "./EnvironmentLinkSchemaSysLinkType.js";
import { EnvironmentLinkSchemaSysType } from "./EnvironmentLinkSchemaSysType.js";

export const EnvironmentLinkSchemaSys: core.serialization.ObjectSchema<
    serializers.EnvironmentLinkSchemaSys.Raw,
    Contentful.EnvironmentLinkSchemaSys
> = core.serialization.object({
    type: EnvironmentLinkSchemaSysType,
    linkType: EnvironmentLinkSchemaSysLinkType,
    id: core.serialization.string(),
});

export declare namespace EnvironmentLinkSchemaSys {
    export interface Raw {
        type: EnvironmentLinkSchemaSysType.Raw;
        linkType: EnvironmentLinkSchemaSysLinkType.Raw;
        id: string;
    }
}
