// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { EnvironmentLinkSchemaSys } from "./EnvironmentLinkSchemaSys.js";

export const EnvironmentLinkSchema: core.serialization.ObjectSchema<
    serializers.EnvironmentLinkSchema.Raw,
    Contentful.EnvironmentLinkSchema
> = core.serialization.object({
    sys: EnvironmentLinkSchemaSys,
});

export declare namespace EnvironmentLinkSchema {
    export interface Raw {
        sys: EnvironmentLinkSchemaSys.Raw;
    }
}
