// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const IsoDateTimeSchema: core.serialization.Schema<
    serializers.IsoDateTimeSchema.Raw,
    Contentful.IsoDateTimeSchema
> = core.serialization.date();

export declare namespace IsoDateTimeSchema {
    export type Raw = string;
}
