// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SpaceLinkSchemaSysType: core.serialization.Schema<
    serializers.SpaceLinkSchemaSysType.Raw,
    Contentful.SpaceLinkSchemaSysType
> = core.serialization.enum_(["Link"]);

export declare namespace SpaceLinkSchemaSysType {
    export type Raw = "Link";
}
