// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const SpaceLinkSchemaSysLinkType: core.serialization.Schema<
    serializers.SpaceLinkSchemaSysLinkType.Raw,
    Contentful.SpaceLinkSchemaSysLinkType
> = core.serialization.enum_(["Space"]);

export declare namespace SpaceLinkSchemaSysLinkType {
    export type Raw = "Space";
}
