// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { SpaceLinkSchemaSys } from "./SpaceLinkSchemaSys.js";

export const SpaceLinkSchema: core.serialization.ObjectSchema<
    serializers.SpaceLinkSchema.Raw,
    Contentful.SpaceLinkSchema
> = core.serialization.object({
    sys: SpaceLinkSchemaSys,
});

export declare namespace SpaceLinkSchema {
    export interface Raw {
        sys: SpaceLinkSchemaSys.Raw;
    }
}
