// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SpaceLinkSchemaSysLinkType } from "./SpaceLinkSchemaSysLinkType.js";
import { SpaceLinkSchemaSysType } from "./SpaceLinkSchemaSysType.js";

export const SpaceLinkSchemaSys: core.serialization.ObjectSchema<
    serializers.SpaceLinkSchemaSys.Raw,
    Contentful.SpaceLinkSchemaSys
> = core.serialization.object({
    type: SpaceLinkSchemaSysType,
    linkType: SpaceLinkSchemaSysLinkType,
    id: core.serialization.string(),
});

export declare namespace SpaceLinkSchemaSys {
    export interface Raw {
        type: SpaceLinkSchemaSysType.Raw;
        linkType: SpaceLinkSchemaSysLinkType.Raw;
        id: string;
    }
}
