// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const TagLinkSchemaSysType: core.serialization.Schema<
    serializers.TagLinkSchemaSysType.Raw,
    Contentful.TagLinkSchemaSysType
> = core.serialization.enum_(["Link"]);

export declare namespace TagLinkSchemaSysType {
    export type Raw = "Link";
}
