// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { TagLinkSchemaSysType } from "./TagLinkSchemaSysType.js";
import { TagLinkSchemaSysLinkType } from "./TagLinkSchemaSysLinkType.js";

export const TagLinkSchemaSys: core.serialization.ObjectSchema<
    serializers.TagLinkSchemaSys.Raw,
    Contentful.TagLinkSchemaSys
> = core.serialization.object({
    type: TagLinkSchemaSysType,
    linkType: TagLinkSchemaSysLinkType,
    id: core.serialization.string(),
});

export declare namespace TagLinkSchemaSys {
    export interface Raw {
        type: TagLinkSchemaSysType.Raw;
        linkType: TagLinkSchemaSysLinkType.Raw;
        id: string;
    }
}
