// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TagLinkSchemaSysLinkType: core.serialization.Schema<
    serializers.TagLinkSchemaSysLinkType.Raw,
    Contentful.TagLinkSchemaSysLinkType
> = core.serialization.enum_(["Tag"]);

export declare namespace TagLinkSchemaSysLinkType {
    export type Raw = "Tag";
}
