// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import { TagLinkSchemaSys } from "./TagLinkSchemaSys.js";

export const TagLinkSchema: core.serialization.ObjectSchema<serializers.TagLinkSchema.Raw, Contentful.TagLinkSchema> =
    core.serialization.object({
        sys: TagLinkSchemaSys,
    });

export declare namespace TagLinkSchema {
    export interface Raw {
        sys: TagLinkSchemaSys.Raw;
    }
}
