// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TaxonomyConceptLinkSchemaSysLinkType } from "./TaxonomyConceptLinkSchemaSysLinkType.js";
import { TaxonomyConceptLinkSchemaSysType } from "./TaxonomyConceptLinkSchemaSysType.js";

export const TaxonomyConceptLinkSchemaSys: core.serialization.ObjectSchema<
    serializers.TaxonomyConceptLinkSchemaSys.Raw,
    Contentful.TaxonomyConceptLinkSchemaSys
> = core.serialization.object({
    type: TaxonomyConceptLinkSchemaSysType,
    linkType: TaxonomyConceptLinkSchemaSysLinkType,
    id: core.serialization.string(),
});

export declare namespace TaxonomyConceptLinkSchemaSys {
    export interface Raw {
        type: TaxonomyConceptLinkSchemaSysType.Raw;
        linkType: TaxonomyConceptLinkSchemaSysLinkType.Raw;
        id: string;
    }
}
