// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const TaxonomyConceptLinkSchemaSysType: core.serialization.Schema<
    serializers.TaxonomyConceptLinkSchemaSysType.Raw,
    Contentful.TaxonomyConceptLinkSchemaSysType
> = core.serialization.enum_(["Link"]);

export declare namespace TaxonomyConceptLinkSchemaSysType {
    export type Raw = "Link";
}
