// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const TaxonomyConceptLinkSchemaSysLinkType: core.serialization.Schema<
    serializers.TaxonomyConceptLinkSchemaSysLinkType.Raw,
    Contentful.TaxonomyConceptLinkSchemaSysLinkType
> = core.serialization.enum_(["TaxonomyConcept"]);

export declare namespace TaxonomyConceptLinkSchemaSysLinkType {
    export type Raw = "TaxonomyConcept";
}
