// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TaxonomyConceptLinkSchemaSys } from "./TaxonomyConceptLinkSchemaSys.js";

export const TaxonomyConceptLinkSchema: core.serialization.ObjectSchema<
    serializers.TaxonomyConceptLinkSchema.Raw,
    Contentful.TaxonomyConceptLinkSchema
> = core.serialization.object({
    sys: TaxonomyConceptLinkSchemaSys,
});

export declare namespace TaxonomyConceptLinkSchema {
    export interface Raw {
        sys: TaxonomyConceptLinkSchemaSys.Raw;
    }
}
