// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const UserLinkSchemaSysType: core.serialization.Schema<
    serializers.UserLinkSchemaSysType.Raw,
    Contentful.UserLinkSchemaSysType
> = core.serialization.enum_(["Link"]);

export declare namespace UserLinkSchemaSysType {
    export type Raw = "Link";
}
