// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../index.js";
import * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";

export const UserLinkSchemaSysLinkType: core.serialization.Schema<
    serializers.UserLinkSchemaSysLinkType.Raw,
    Contentful.UserLinkSchemaSysLinkType
> = core.serialization.enum_(["User"]);

export declare namespace UserLinkSchemaSysLinkType {
    export type Raw = "User";
}
