// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserLinkSchemaSysLinkType } from "./UserLinkSchemaSysLinkType.js";
import { UserLinkSchemaSysType } from "./UserLinkSchemaSysType.js";

export const UserLinkSchemaSys: core.serialization.ObjectSchema<
    serializers.UserLinkSchemaSys.Raw,
    Contentful.UserLinkSchemaSys
> = core.serialization.object({
    type: UserLinkSchemaSysType,
    linkType: UserLinkSchemaSysLinkType,
    id: core.serialization.string(),
});

export declare namespace UserLinkSchemaSys {
    export interface Raw {
        type: UserLinkSchemaSysType.Raw;
        linkType: UserLinkSchemaSysLinkType.Raw;
        id: string;
    }
}
