// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserLinkSchemaSys } from "./UserLinkSchemaSys.js";

export const UserLinkSchema: core.serialization.ObjectSchema<
    serializers.UserLinkSchema.Raw,
    Contentful.UserLinkSchema
> = core.serialization.object({
    sys: UserLinkSchemaSys,
});

export declare namespace UserLinkSchema {
    export interface Raw {
        sys: UserLinkSchemaSys.Raw;
    }
}
