// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ListContentTypesResponseSysType } from "./ListContentTypesResponseSysType.js";

export const ListContentTypesResponseSys: core.serialization.ObjectSchema<
    serializers.ListContentTypesResponseSys.Raw,
    Contentful.ListContentTypesResponseSys
> = core.serialization.object({
    type: ListContentTypesResponseSysType,
});

export declare namespace ListContentTypesResponseSys {
    export interface Raw {
        type: ListContentTypesResponseSysType.Raw;
    }
}
