// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ContentTypeSchema } from "../../../types/ContentTypeSchema.js";
import { ListContentTypesResponseIncludes } from "./ListContentTypesResponseIncludes.js";
import { ListContentTypesResponseSys } from "./ListContentTypesResponseSys.js";

export const ListContentTypesResponse: core.serialization.ObjectSchema<
    serializers.ListContentTypesResponse.Raw,
    Contentful.ListContentTypesResponse
> = core.serialization.object({
    sys: ListContentTypesResponseSys,
    total: core.serialization.number(),
    skip: core.serialization.number(),
    limit: core.serialization.number(),
    items: core.serialization.list(ContentTypeSchema),
    includes: ListContentTypesResponseIncludes.optional(),
});

export declare namespace ListContentTypesResponse {
    export interface Raw {
        sys: ListContentTypesResponseSys.Raw;
        total: number;
        skip: number;
        limit: number;
        items: ContentTypeSchema.Raw[];
        includes?: ListContentTypesResponseIncludes.Raw | null;
    }
}
