// This file was auto-generated by Fern from our API Definition.

import type * as Contentful from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ContentTypeSchema } from "../../../types/ContentTypeSchema.js";

export const ListContentTypesResponseIncludes: core.serialization.ObjectSchema<
    serializers.ListContentTypesResponseIncludes.Raw,
    Contentful.ListContentTypesResponseIncludes
> = core.serialization.object({
    entry: core.serialization.property("Entry", core.serialization.list(ContentTypeSchema).optional()),
    asset: core.serialization.property("Asset", core.serialization.list(core.serialization.unknown()).optional()),
});

export declare namespace ListContentTypesResponseIncludes {
    export interface Raw {
        Entry?: ContentTypeSchema.Raw[] | null;
        Asset?: unknown[] | null;
    }
}
