// This file was auto-generated by Fern from our API Definition.

import { ContentfulClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContentTypesClient", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ContentfulClient({
            maxRetries: 0,
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
            token: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            sys: {
                space: { sys: { type: "Link", linkType: "Space", id: "exampleSpaceId" } },
                id: "blogPost",
                type: { sys: { type: "Link", linkType: "ContentType", id: "ContentType" } },
                createdAt: "2023-10-05T14:48:00Z",
                updatedAt: "2023-10-05T14:48:00Z",
                environment: { sys: { type: "Link", linkType: "Environment", id: "master" } },
                publishedVersion: 1,
                publishedAt: "2023-10-05T14:48:00Z",
                firstPublishedAt: "2023-10-05T14:48:00Z",
                createdBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                updatedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                publishedCounter: 1,
                version: 1,
                publishedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
            },
            displayField: "title",
            name: "Blog Post",
            description: "A content type for blog posts",
            fields: [
                {
                    id: "title",
                    type: "Symbol",
                    name: "Title",
                    localized: true,
                    required: true,
                    disabled: true,
                    omitted: true,
                    deleted: true,
                    items: { type: "Symbol" },
                    linkType: "Asset",
                    defaultValue: { key: "value" },
                },
            ],
            metadata: {
                annotations: [{ key: "value" }],
                taxonomy: [{ sys: { type: "Link", linkType: "TaxonomyConcept", id: "id" } }],
            },
        };
        server
            .mockEndpoint()
            .get("/spaces/yadj1kx9rmg0/environments/master/content_types/blogPost")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contentTypes.get({
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
            contentTypeId: "blogPost",
        });
        expect(response).toEqual({
            sys: {
                space: {
                    sys: {
                        type: "Link",
                        linkType: "Space",
                        id: "exampleSpaceId",
                    },
                },
                id: "blogPost",
                type: {
                    sys: {
                        type: "Link",
                        linkType: "ContentType",
                        id: "ContentType",
                    },
                },
                createdAt: new Date("2023-10-05T14:48:00.000Z"),
                updatedAt: new Date("2023-10-05T14:48:00.000Z"),
                environment: {
                    sys: {
                        type: "Link",
                        linkType: "Environment",
                        id: "master",
                    },
                },
                publishedVersion: 1,
                publishedAt: new Date("2023-10-05T14:48:00.000Z"),
                firstPublishedAt: new Date("2023-10-05T14:48:00.000Z"),
                createdBy: {
                    sys: {
                        type: "Link",
                        linkType: "User",
                        id: "exampleUserId",
                    },
                },
                updatedBy: {
                    sys: {
                        type: "Link",
                        linkType: "User",
                        id: "exampleUserId",
                    },
                },
                publishedCounter: 1,
                version: 1,
                publishedBy: {
                    sys: {
                        type: "Link",
                        linkType: "User",
                        id: "exampleUserId",
                    },
                },
            },
            displayField: "title",
            name: "Blog Post",
            description: "A content type for blog posts",
            fields: [
                {
                    id: "title",
                    type: "Symbol",
                    name: "Title",
                    localized: true,
                    required: true,
                    disabled: true,
                    omitted: true,
                    deleted: true,
                    items: {
                        type: "Symbol",
                    },
                    linkType: "Asset",
                    defaultValue: {
                        key: "value",
                    },
                },
            ],
            metadata: {
                annotations: [
                    {
                        key: "value",
                    },
                ],
                taxonomy: [
                    {
                        sys: {
                            type: "Link",
                            linkType: "TaxonomyConcept",
                            id: "id",
                        },
                    },
                ],
            },
        });
    });

    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new ContentfulClient({
            maxRetries: 0,
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
            token: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            sys: { type: "Array" },
            total: 1,
            skip: 0,
            limit: 1,
            items: [
                {
                    sys: {
                        space: { sys: { type: "Link", linkType: "Space", id: "exampleSpaceId" } },
                        id: "blogPost",
                        type: { sys: { type: "Link", linkType: "ContentType", id: "ContentType" } },
                        createdAt: "2023-10-05T14:48:00Z",
                        updatedAt: "2023-10-05T14:48:00Z",
                        environment: { sys: { type: "Link", linkType: "Environment", id: "master" } },
                        publishedVersion: 1,
                        publishedAt: "2023-10-05T14:48:00Z",
                        firstPublishedAt: "2023-10-05T14:48:00Z",
                        createdBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                        updatedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                        publishedCounter: 1,
                        version: 1,
                        publishedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                    },
                    displayField: "title",
                    name: "Blog Post",
                    description: "A content type for blog posts",
                    fields: [{ id: "title", type: "Symbol", name: "Title", required: true }],
                },
            ],
            includes: {
                Entry: [
                    {
                        sys: {
                            space: { sys: { type: "Link", linkType: "Space", id: "id" } },
                            id: "id",
                            type: { sys: { type: "Link", linkType: "ContentType", id: "id" } },
                            createdAt: "2024-01-15T09:30:00Z",
                            updatedAt: "2024-01-15T09:30:00Z",
                            environment: { sys: { type: "Link", linkType: "Environment", id: "id" } },
                            createdBy: { sys: { type: "Link", linkType: "User", id: "id" } },
                            updatedBy: { sys: { type: "Link", linkType: "User", id: "id" } },
                            publishedCounter: 1.1,
                            version: 1.1,
                        },
                        name: "name",
                        fields: [{ id: "id", type: "Symbol", name: "name" }],
                    },
                ],
                Asset: [{ key: "value" }],
            },
        };
        server
            .mockEndpoint()
            .get("/spaces/yadj1kx9rmg0/environments/master/content_types")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contentTypes.list({
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
        });
        expect(response).toEqual({
            sys: {
                type: "Array",
            },
            total: 1,
            skip: 0,
            limit: 1,
            items: [
                {
                    sys: {
                        space: {
                            sys: {
                                type: "Link",
                                linkType: "Space",
                                id: "exampleSpaceId",
                            },
                        },
                        id: "blogPost",
                        type: {
                            sys: {
                                type: "Link",
                                linkType: "ContentType",
                                id: "ContentType",
                            },
                        },
                        createdAt: new Date("2023-10-05T14:48:00.000Z"),
                        updatedAt: new Date("2023-10-05T14:48:00.000Z"),
                        environment: {
                            sys: {
                                type: "Link",
                                linkType: "Environment",
                                id: "master",
                            },
                        },
                        publishedVersion: 1,
                        publishedAt: new Date("2023-10-05T14:48:00.000Z"),
                        firstPublishedAt: new Date("2023-10-05T14:48:00.000Z"),
                        createdBy: {
                            sys: {
                                type: "Link",
                                linkType: "User",
                                id: "exampleUserId",
                            },
                        },
                        updatedBy: {
                            sys: {
                                type: "Link",
                                linkType: "User",
                                id: "exampleUserId",
                            },
                        },
                        publishedCounter: 1,
                        version: 1,
                        publishedBy: {
                            sys: {
                                type: "Link",
                                linkType: "User",
                                id: "exampleUserId",
                            },
                        },
                    },
                    displayField: "title",
                    name: "Blog Post",
                    description: "A content type for blog posts",
                    fields: [
                        {
                            id: "title",
                            type: "Symbol",
                            name: "Title",
                            required: true,
                        },
                    ],
                },
            ],
            includes: {
                entry: [
                    {
                        sys: {
                            space: {
                                sys: {
                                    type: "Link",
                                    linkType: "Space",
                                    id: "id",
                                },
                            },
                            id: "id",
                            type: {
                                sys: {
                                    type: "Link",
                                    linkType: "ContentType",
                                    id: "id",
                                },
                            },
                            createdAt: new Date("2024-01-15T09:30:00.000Z"),
                            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                            environment: {
                                sys: {
                                    type: "Link",
                                    linkType: "Environment",
                                    id: "id",
                                },
                            },
                            createdBy: {
                                sys: {
                                    type: "Link",
                                    linkType: "User",
                                    id: "id",
                                },
                            },
                            updatedBy: {
                                sys: {
                                    type: "Link",
                                    linkType: "User",
                                    id: "id",
                                },
                            },
                            publishedCounter: 1.1,
                            version: 1.1,
                        },
                        name: "name",
                        fields: [
                            {
                                id: "id",
                                type: "Symbol",
                                name: "name",
                            },
                        ],
                    },
                ],
                asset: [
                    {
                        key: "value",
                    },
                ],
            },
        });
    });
});
