// This file was auto-generated by Fern from our API Definition.

import { ContentfulClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EntriesClient", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ContentfulClient({
            maxRetries: 0,
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
            token: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            metadata: {
                tags: [{ sys: { type: "Link", linkType: "Tag", id: "exampleTagId" } }],
                concepts: [{ sys: { type: "Link", linkType: "TaxonomyConcept", id: "exampleTaxonomyConceptId" } }],
            },
            sys: {
                space: { sys: { type: "Link", linkType: "Space", id: "exampleSpaceId" } },
                id: "exampleEntryId",
                type: "Entry",
                createdAt: "2023-10-05T14:48:00Z",
                updatedAt: "2023-10-05T14:48:00Z",
                environment: { sys: { type: "Link", linkType: "Environment", id: "master" } },
                publishedVersion: 3,
                publishedAt: "2023-10-06T10:00:00Z",
                firstPublishedAt: "2023-10-05T15:00:00Z",
                createdBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                updatedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                publishedCounter: 2,
                version: 3,
                publishedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                fieldStatus: { "*": { title: "published", description: "draft", body: "changed" } },
                automationTags: [
                    { sys: { type: "Link", linkType: "Tag", id: "automationTagId1" } },
                    { sys: { type: "Link", linkType: "Tag", id: "automationTagId2" } },
                ],
                contentType: { sys: { type: "Link", linkType: "ContentType", id: "blogPost" } },
                urn: "urn:contentful:entry::exampleEntryId",
            },
            fields: {
                title: { key: "value" },
                description: { key: "value" },
                body: { key: "value" },
                relatedEntries: {
                    "0": { sys: { type: "Link", linkType: "Entry", id: "relatedEntryId1" } },
                    "1": { sys: { type: "Link", linkType: "Entry", id: "relatedEntryId2" } },
                },
                tags: { "0": { sys: { type: "Link", linkType: "Entry", id: "exampleTagId" } } },
            },
        };
        server
            .mockEndpoint()
            .get("/spaces/yadj1kx9rmg0/environments/master/entries/1nG4SkuMy0WenQUG6z2aEw")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entries.get({
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
            entryId: "1nG4SkuMy0WenQUG6z2aEw",
        });
        expect(response).toEqual({
            metadata: {
                tags: [
                    {
                        sys: {
                            type: "Link",
                            linkType: "Tag",
                            id: "exampleTagId",
                        },
                    },
                ],
                concepts: [
                    {
                        sys: {
                            type: "Link",
                            linkType: "TaxonomyConcept",
                            id: "exampleTaxonomyConceptId",
                        },
                    },
                ],
            },
            sys: {
                space: {
                    sys: {
                        type: "Link",
                        linkType: "Space",
                        id: "exampleSpaceId",
                    },
                },
                id: "exampleEntryId",
                type: "Entry",
                createdAt: new Date("2023-10-05T14:48:00.000Z"),
                updatedAt: new Date("2023-10-05T14:48:00.000Z"),
                environment: {
                    sys: {
                        type: "Link",
                        linkType: "Environment",
                        id: "master",
                    },
                },
                publishedVersion: 3,
                publishedAt: new Date("2023-10-06T10:00:00.000Z"),
                firstPublishedAt: new Date("2023-10-05T15:00:00.000Z"),
                createdBy: {
                    sys: {
                        type: "Link",
                        linkType: "User",
                        id: "exampleUserId",
                    },
                },
                updatedBy: {
                    sys: {
                        type: "Link",
                        linkType: "User",
                        id: "exampleUserId",
                    },
                },
                publishedCounter: 2,
                version: 3,
                publishedBy: {
                    sys: {
                        type: "Link",
                        linkType: "User",
                        id: "exampleUserId",
                    },
                },
                fieldStatus: {
                    properties: {
                        title: "published",
                        description: "draft",
                        body: "changed",
                    },
                },
                automationTags: [
                    {
                        sys: {
                            type: "Link",
                            linkType: "Tag",
                            id: "automationTagId1",
                        },
                    },
                    {
                        sys: {
                            type: "Link",
                            linkType: "Tag",
                            id: "automationTagId2",
                        },
                    },
                ],
                contentType: {
                    sys: {
                        type: "Link",
                        linkType: "ContentType",
                        id: "blogPost",
                    },
                },
                urn: "urn:contentful:entry::exampleEntryId",
            },
            fields: {
                title: {
                    key: "value",
                },
                description: {
                    key: "value",
                },
                body: {
                    key: "value",
                },
                relatedEntries: {
                    "0": {
                        sys: {
                            type: "Link",
                            linkType: "Entry",
                            id: "relatedEntryId1",
                        },
                    },
                    "1": {
                        sys: {
                            type: "Link",
                            linkType: "Entry",
                            id: "relatedEntryId2",
                        },
                    },
                },
                tags: {
                    "0": {
                        sys: {
                            type: "Link",
                            linkType: "Entry",
                            id: "exampleTagId",
                        },
                    },
                },
            },
        });
    });

    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new ContentfulClient({
            maxRetries: 0,
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
            token: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            sys: { type: "Array" },
            total: 1,
            skip: 0,
            limit: 1,
            items: [
                {
                    metadata: {
                        tags: [{ sys: { type: "Link", linkType: "Tag", id: "exampleTagId" } }],
                        concepts: [
                            { sys: { type: "Link", linkType: "TaxonomyConcept", id: "exampleTaxonomyConceptId" } },
                        ],
                    },
                    sys: {
                        space: { sys: { type: "Link", linkType: "Space", id: "exampleSpaceId" } },
                        id: "exampleEntryId",
                        type: "Entry",
                        createdAt: "2023-10-05T14:48:00Z",
                        updatedAt: "2023-10-05T14:48:00Z",
                        environment: { sys: { type: "Link", linkType: "Environment", id: "master" } },
                        publishedVersion: 3,
                        publishedAt: "2023-10-06T10:00:00Z",
                        firstPublishedAt: "2023-10-05T15:00:00Z",
                        createdBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                        updatedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                        publishedCounter: 2,
                        version: 3,
                        publishedBy: { sys: { type: "Link", linkType: "User", id: "exampleUserId" } },
                        fieldStatus: { "*": { title: "published", description: "draft", body: "changed" } },
                        automationTags: [
                            { sys: { type: "Link", linkType: "Tag", id: "automationTagId1" } },
                            { sys: { type: "Link", linkType: "Tag", id: "automationTagId2" } },
                        ],
                        contentType: { sys: { type: "Link", linkType: "ContentType", id: "blogPost" } },
                        urn: "urn:contentful:entry::exampleEntryId",
                    },
                    fields: {
                        title: { key: "value" },
                        description: { key: "value" },
                        body: { key: "value" },
                        relatedEntries: {
                            "0": { sys: { type: "Link", linkType: "Entry", id: "relatedEntryId1" } },
                            "1": { sys: { type: "Link", linkType: "Entry", id: "relatedEntryId2" } },
                        },
                        tags: { "0": { sys: { type: "Link", linkType: "Entry", id: "exampleTagId" } } },
                    },
                },
            ],
            includes: {
                Entry: [
                    {
                        metadata: { tags: [{ sys: { type: "Link", linkType: "Tag", id: "id" } }] },
                        sys: {
                            space: { sys: { type: "Link", linkType: "Space", id: "id" } },
                            id: "id",
                            type: "type",
                            createdAt: "2024-01-15T09:30:00Z",
                            updatedAt: "2024-01-15T09:30:00Z",
                            environment: { sys: { type: "Link", linkType: "Environment", id: "id" } },
                            contentType: { sys: { type: "Link", linkType: "ContentType", id: "id" } },
                        },
                        fields: { key: { key: "value" } },
                    },
                ],
                Asset: [{ key: "value" }],
            },
        };
        server
            .mockEndpoint()
            .get("/spaces/yadj1kx9rmg0/environments/master/entries")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entries.list({
            spaceId: "yadj1kx9rmg0",
            environmentId: "master",
            contentType: "blogPost",
        });
        expect(response).toEqual({
            sys: {
                type: "Array",
            },
            total: 1,
            skip: 0,
            limit: 1,
            items: [
                {
                    metadata: {
                        tags: [
                            {
                                sys: {
                                    type: "Link",
                                    linkType: "Tag",
                                    id: "exampleTagId",
                                },
                            },
                        ],
                        concepts: [
                            {
                                sys: {
                                    type: "Link",
                                    linkType: "TaxonomyConcept",
                                    id: "exampleTaxonomyConceptId",
                                },
                            },
                        ],
                    },
                    sys: {
                        space: {
                            sys: {
                                type: "Link",
                                linkType: "Space",
                                id: "exampleSpaceId",
                            },
                        },
                        id: "exampleEntryId",
                        type: "Entry",
                        createdAt: new Date("2023-10-05T14:48:00.000Z"),
                        updatedAt: new Date("2023-10-05T14:48:00.000Z"),
                        environment: {
                            sys: {
                                type: "Link",
                                linkType: "Environment",
                                id: "master",
                            },
                        },
                        publishedVersion: 3,
                        publishedAt: new Date("2023-10-06T10:00:00.000Z"),
                        firstPublishedAt: new Date("2023-10-05T15:00:00.000Z"),
                        createdBy: {
                            sys: {
                                type: "Link",
                                linkType: "User",
                                id: "exampleUserId",
                            },
                        },
                        updatedBy: {
                            sys: {
                                type: "Link",
                                linkType: "User",
                                id: "exampleUserId",
                            },
                        },
                        publishedCounter: 2,
                        version: 3,
                        publishedBy: {
                            sys: {
                                type: "Link",
                                linkType: "User",
                                id: "exampleUserId",
                            },
                        },
                        fieldStatus: {
                            properties: {
                                title: "published",
                                description: "draft",
                                body: "changed",
                            },
                        },
                        automationTags: [
                            {
                                sys: {
                                    type: "Link",
                                    linkType: "Tag",
                                    id: "automationTagId1",
                                },
                            },
                            {
                                sys: {
                                    type: "Link",
                                    linkType: "Tag",
                                    id: "automationTagId2",
                                },
                            },
                        ],
                        contentType: {
                            sys: {
                                type: "Link",
                                linkType: "ContentType",
                                id: "blogPost",
                            },
                        },
                        urn: "urn:contentful:entry::exampleEntryId",
                    },
                    fields: {
                        title: {
                            key: "value",
                        },
                        description: {
                            key: "value",
                        },
                        body: {
                            key: "value",
                        },
                        relatedEntries: {
                            "0": {
                                sys: {
                                    type: "Link",
                                    linkType: "Entry",
                                    id: "relatedEntryId1",
                                },
                            },
                            "1": {
                                sys: {
                                    type: "Link",
                                    linkType: "Entry",
                                    id: "relatedEntryId2",
                                },
                            },
                        },
                        tags: {
                            "0": {
                                sys: {
                                    type: "Link",
                                    linkType: "Entry",
                                    id: "exampleTagId",
                                },
                            },
                        },
                    },
                },
            ],
            includes: {
                entry: [
                    {
                        metadata: {
                            tags: [
                                {
                                    sys: {
                                        type: "Link",
                                        linkType: "Tag",
                                        id: "id",
                                    },
                                },
                            ],
                        },
                        sys: {
                            space: {
                                sys: {
                                    type: "Link",
                                    linkType: "Space",
                                    id: "id",
                                },
                            },
                            id: "id",
                            type: "type",
                            createdAt: new Date("2024-01-15T09:30:00.000Z"),
                            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                            environment: {
                                sys: {
                                    type: "Link",
                                    linkType: "Environment",
                                    id: "id",
                                },
                            },
                            contentType: {
                                sys: {
                                    type: "Link",
                                    linkType: "ContentType",
                                    id: "id",
                                },
                            },
                        },
                        fields: {
                            key: {
                                key: "value",
                            },
                        },
                    },
                ],
                asset: [
                    {
                        key: "value",
                    },
                ],
            },
        });
    });
});
