// This file was auto-generated by Fern from our API Definition.

import { ContentTypesClient } from "./api/resources/contentTypes/client/Client.js";
import { EntriesClient } from "./api/resources/entries/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace ContentfulClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ContentfulClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ContentfulClient.Options>;
    protected _contentTypes: ContentTypesClient | undefined;
    protected _entries: EntriesClient | undefined;

    constructor(options: ContentfulClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get contentTypes(): ContentTypesClient {
        return (this._contentTypes ??= new ContentTypesClient(this._options));
    }

    public get entries(): EntriesClient {
        return (this._entries ??= new EntriesClient(this._options));
    }
}
