// This file was auto-generated by Fern from our API Definition.

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { ContentTypes } from "./api/resources/contentTypes/client/Client.js";
import { Entries } from "./api/resources/entries/client/Client.js";

export declare namespace ContentfulClient {
    export interface Options {
        environment?: core.Supplier<environments.ContentfulEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        spaceId: string;
        environmentId: string;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class ContentfulClient {
    protected readonly _options: ContentfulClient.Options;
    protected _contentTypes: ContentTypes | undefined;
    protected _entries: Entries | undefined;

    constructor(_options: ContentfulClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "contentful",
                    "X-Fern-SDK-Version": "11.10.2",
                    "User-Agent": "contentful/11.10.2",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get contentTypes(): ContentTypes {
        return (this._contentTypes ??= new ContentTypes(this._options));
    }

    public get entries(): Entries {
        return (this._entries ??= new Entries(this._options));
    }
}
