// This file was auto-generated by Fern from our API Definition.

export const ContentfulEnvironment = {
    Default: "https://cdn.contentful.com",
} as const;

export type ContentfulEnvironment = typeof ContentfulEnvironment.Default;
